"""Build a fully hash-locked requirements file (DEP-001).

Exact top-level pins do not lock TRANSITIVE dependencies: `uvicorn[standard]`
alone pulls a dozen version ranges, so two installs of the same
requirements.txt can resolve to different code - and pip executes whatever it
downloads, as the service user that owns secret.key and the database.

This asks pip's own resolver for the closure of requirements.txt, downloads
every artifact in it, and writes each one with its sha256, so installs can
use `--require-hashes --no-deps`.

Usage:  python tools_lock.py
"""
import hashlib
import io
import json
import os
import re
import shutil
import subprocess
import sys

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

PY = sys.executable
REQ = "requirements.txt"
LOCK = "requirements.lock"
REPORT = ".lockreport.json"
HOUSE = ".lockhouse"


def run(args, **kw):
    return subprocess.run([PY, "-m", "pip", *args], capture_output=True,
                          text=True, timeout=1800, **kw)


wanted = [ln.strip() for ln in io.open(REQ, encoding="utf-8")
          if ln.strip() and not ln.strip().startswith("#")]

# ---- 1. resolve the real closure (not "whatever is in this venv": that
#         would lock dev tooling like pip-audit into production installs)
for stale in (REPORT,):
    if os.path.exists(stale):
        os.remove(stale)
res = run(["install", "--dry-run", "--ignore-installed", "--report", REPORT,
           "-r", REQ])
if res.returncode != 0 or not os.path.isfile(REPORT):
    print("resolution failed:", (res.stderr or res.stdout)[-900:])
    sys.exit(1)

pins, extras_of = {}, {}
for item in json.load(io.open(REPORT, encoding="utf-8")).get("install", []):
    meta = item.get("metadata", {})
    name = (meta.get("name") or "").lower()
    ver = meta.get("version") or ""
    if not (name and ver):
        continue
    pins[name] = ver
    if meta.get("requested_extras"):
        extras_of[name] = ",".join(meta["requested_extras"])

direct = []
for spec in wanted:
    base = spec.split("[")[0].split("==")[0].strip().lower()
    if base in pins:
        direct.append(base)
    else:
        print("WARN unresolved:", spec)
print(f"closure: {len(pins)} packages ({len(direct)} direct)")

# ---- 2. hash every artifact
shutil.rmtree(HOUSE, ignore_errors=True)
specs = [f"{n}=={v}" for n, v in sorted(pins.items())]
dl = run(["download", "--dest", HOUSE, "--no-deps", *specs])
if dl.returncode != 0:
    print("download warnings:", (dl.stderr or dl.stdout)[-400:])

hashes: dict[str, str] = {}
name_of: dict[str, str] = {}
for fn in sorted(os.listdir(HOUSE) if os.path.isdir(HOUSE) else []):
    if not fn.endswith((".whl", ".tar.gz", ".zip")):
        continue
    with open(os.path.join(HOUSE, fn), "rb") as fh:
        hashes[fn] = hashlib.sha256(fh.read()).hexdigest()
    m = re.match(r"^([A-Za-z0-9_.\-]+?)-(\d[^-]*)", fn)
    if m:
        name_of[fn] = re.sub(r"[-_.]+", "-", m.group(1)).lower()

# Some packages ship no wheel for the interpreter we happen to run on (here:
# CPython 3.14), so a platform-naive download finds nothing for them and the
# lock would be incomplete - a Linux install would then abort under
# --require-hashes. Ask PyPI directly for every artifact of those versions and
# hash the ones a real deployment could pull (wheels + sdist).
from urllib.request import Request as _Req, urlopen as _open

PY_TAGS = {
    "cp312": "any", "cp313": "any", "abi3": "any", "py3": "any",
    "pp39": "any", "pp310": "any",
}


def pypi_hashes(project: str, version: str) -> list[str]:
    """sha256 of every PyPI artifact for one release (name-version scoped)."""
    out: list[str] = []
    try:
        url = f"https://pypi.org/pypi/{project}/{version}/json"
        with _open(_Req(url, headers={"User-Agent": "zefira-lock"}), timeout=45) as r:
            meta = json.loads(r.read().decode())
    except Exception as exc:
        print(f"  pypi lookup failed for {project}=={version}: {exc}")
        return out
    base = re.sub(r"[-_.]+", "-", project).lower()
    for entry in meta.get("urls", []):
        fn = entry.get("filename", "")
        if not fn.endswith((".whl", ".tar.gz", ".zip")):
            continue
        # Keep EVERY artifact: extra hashes are harmless (pip selects the one
        # compatible with the target and checks it against the list) and a
        # filter that drops the cp3xx/musllinux wheel leaves only an sdist,
        # which then has to be BUILT on the server (needs a Rust/Go toolchain
        # for pydantic-core, httptools, watchfiles...).
        digest = entry.get("digests", {}).get("sha256")
        if digest:
            out.append(digest)
    return sorted(set(out))

# ---- 3. write the lock
out = [
    "# Hash-locked dependency set - generated by tools_lock.py, do not hand-edit.",
    "#",
    "# Every artifact, direct AND transitive, is pinned with its sha256:",
    "#     pip install --require-hashes --no-deps -r requirements.lock",
    "# aborts on anything that is not the exact file we hashed. Exact top-level",
    "# pins in requirements.txt never did that: `uvicorn[standard]` alone pulls",
    "# a dozen version ranges, so each install could execute different code.",
    "#",
    "# requirements.txt = the human-maintained direct pins (what to upgrade on",
    "# purpose). This file = what install.sh and the in-panel updater install.",
    "#",
    "# Regenerate after editing requirements.txt:  python tools_lock.py",
    "",
]
unhashed = []
for name, ver in sorted(pins.items()):
    arts = sorted(fn for fn in hashes if name_of.get(fn) == name)
    extras = ("[" + extras_of[name] + "]") if name in extras_of else ""
    digests = sorted({hashes[fn] for fn in arts})
    if not digests:
        # No artifact for THIS interpreter: take every release artifact PyPI
        # publishes, so a server on another Python still resolves.
        digests = pypi_hashes(name, ver)
    if not digests:
        unhashed.append(name)
        out.append(f"# UNHASHED (no artifact found upstream): {name}=={ver}")
        continue
    out.append(f"{name}{extras}=={ver} \\")
    for i, h in enumerate(digests):
        last = i == len(digests) - 1
        out.append(f"    --hash=sha256:{h}" + ("" if last else " \\"))

io.open(LOCK, "w", encoding="utf-8", newline="\n").write("\n".join(out) + "\n")
shutil.rmtree(HOUSE, ignore_errors=True)
if os.path.exists(REPORT):
    os.remove(REPORT)
print(f"wrote {LOCK}: {len(pins) - len(unhashed)} hashed, {len(unhashed)} unhashed")
for u in unhashed:
    print("  unhashed:", u)
sys.exit(1 if unhashed else 0)
